server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    root /var/www/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    # Tangkap API Backend Laravel
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Jalur Fallback untuk Semua Halaman Frontend React SPA
    location / {
        root /var/www/public/client;
        try_files $uri $uri/ /index.html;
    }

    # Eksekusi PHP via PHP-FPM untuk Laravel
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
